CONTRIBUTING.md, README.md
- Standardized spacing after headers.
- Fixed typos in README.md.
- Added some clarification in grammar used in CONTRIBUTING.md and README.md to improve clarity.
=> fix typos and grammatical errors in README and CONTRIBUTING files

govultr.go, govultr_test.go
This PR fixes a panic when `http.Client.Do` returns an error. This issue is caused by trying to close the request body with defer before checking for an error (see golang/go#17780).
I noticed this issue when running dnscontrol (PR StackExchange/dnscontrol#529) on my CI server, and I forgot to install `ca-certificates` in the image (resulting in the error: `Get https://api.vultr.com/v1/account/info: x509: certificate signed by unknown authority`).
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xd277ae]
goroutine 1 [running]:
github.com/StackExchange/dnscontrol/vendor/github.com/vultr/govultr.(*Client).DoWithContext(0xc0006e4680, 0x11d8e60, 0xc0000b4030, 0xc0001c6800, 0xdd0d00, 0xc000295480, 0x0, …
```
=> Fix panic on request failure

.travis.yml
Go 1.13 has been released. Dropping support for go 1.10 and updating travis-ci
none
=> removing go 1.10 and adding 1.13 in travis

.travis.yml, go.mod, go.sum, govultr.go, govultr_test.go
Implements exponential backoff for rate-limited requests to deal with low API rate-limit.
Based on #27. Still not the cleanest code, but is the bare minimum to implement retry correctly. See https://github.com/vultr/govultr/pull/27#pullrequestreview-311920776. I will be submitting another PR with a lot more refactoring when I have time.
closes #26, closes #27
=> Retry rate-limited requests with exponential backoff

dns_records.go, dns_records_test.go
This will fix a bug in which you were not able to update the priority of a record to 0. It will introduce a backwards breaking change since now priority in the DNS Records struct will be a pointer to an int.
=> DNS Record Update Priority

server.go, server_test.go
AddIPv4 will now return the IP address that was just created.
Closes #76
=> AddIPv4 returns change

bare_metal_server.go, bare_metal_server_test.go
Use same param name for activation emails in bare metal and instances
=> change param name for bm to match instances

load_balancer.go
Remove field `stickySessionsEnabled` from the stickysession struct in LBs. This is no longer needed in v2
=> v2 - lb removing enable sticky sessions param

bare_metal_server.go, bare_metal_server_test.go, server.go, server_test.go
Don't not base64 encode userdata on server and bare-metal creation. This matches behaviour from #73.
- [terraform-provider-vultr #68](https://github.com/vultr/terraform-provider-vultr/issues/68)
=> Remove base64 encoding of user data on create

README.md, bare_metal_server.go, bare_metal_server_test.go, go.sum
updates paging description, add bm start call
=> add bm start call, update paging description

.codecov.yml, .github/workflows/gochecks.yml, bare_metal_server_test.go, govultr.go, govultr_test.go, instance.go, instance_test.go, load_balancer_test.go, network_test.go, user.go
- Adding gofmt and golint checks to PRs
- Added missing unit tests and more tests for govultr_test.go
- Fixed typo in URI for detach private networks in instances (bug)
n/a
=> Unit tests & CI checks

plans.go, plans_test.go
The field `disk_count` was added to all plans for instances and baremetal. This denotes how many disks are available with the plan
=> Plans Update : adding disk_count

block_storage.go, block_storage_test.go
Block storage has a new field called `mount_id` which tells you which ID will be mounted on the instance in `/dev/disk/by-id/`
=> Block : add mount_id field

README.md
This PR updates the **Create a VPS** sample in the project README file to utilise what I believe to be correct syntax for the V2 Vultr Go client.  
**Note**: I am using the goVultr API as a learning tool to learn go, as such I am unfamiliar with go syntax/idioms. 
When using the sample, I found the following issues.
Creating an instance requires a `InstanceCreateReq` struct to be passed into the call to `Create` rather than `InstanceReq` struct
https://github.com/vultr/govultr/blob/019c4d29bf308a32888c6b93094925f69164c281/instance.go#L251
The `Backups` property on `InstanceCreateReq` appears to be a `string` rather than `bool` 
https://github.com/vultr/govultr/blob/019c4d29bf308a32888c6b93094925f69164c281/instance.go#L226
The `EnableIPv6` property on `InstanceCreateReq` appears to be a …
=> Update 'Create a VPS' usage sample

instance.go, instance_test.go
The `listPrivateNetworks` call allows for paging on the API and we return the metadata in the go library. However, you can't pass in paging information to the function. This adds paging ability
n/a
=> Instances : ListPrivateNetworks missing paging ability

application.go, application_test.go, bare_metal_server.go, bare_metal_server_test.go, instance.go, instance_test.go
Add marketplace support for application listing and deployment support for instances + bm
n/a
=> Marketplace support 

kubernetes.go, kubernetes_test.go
Adds support for deleting kubernetes cluster with linked resources and getting supported kubernetes versions
=> K8 endpoint updates

snapshot.go, snapshot_test.go
=> add snapshot compressed size

CHANGELOG.md, govultr.go
=> release v2.9.0

instance.go, instance_test.go
This is a slight breaking change as the new version for govultr will require users to add in the new param
This will add in the ability for users to change the hostname during and install which is available on the API call
https://www.vultr.com/api/#operation/reinstall-instance
#180
=> Instance : add optional fields for reinstall call

instance.go, instance_test.go
Instance update calls will now return the instance data 
Addresses #182
=> Instance update will return instance data

CHANGELOG.md, govultr.go
Release for v2.11.0
#184 #187 #181 #182
=> release for v2.11.0

.github/workflows/coverage.yml
updates when coverage test is run
=> run tests on master

listOptions.go, snapshot.go
We added two new features to the API 
1. Added the ability to filter snapshots by description in the list call
2. Ability to add descriptions to snapshots from the createFromUrl call
=> Snapshot : new features

govultr.go
Improving the retry error response to include the error if it is available. This will make debugging issues if a retry had been triggered easier
https://github.com/vultr/terraform-provider-vultr/issues/209
=> Improved retry error response

instance.go, instance_test.go
Restore instance request (v2) is passing a nil body (disregarding the method argument)
=> Restore v2 endpoint fix

block_storage.go, block_storage_test.go
Adding the new block_type field. This is an optional param now but may become required in the future as the block storage options grow.
=> block storage: adding block type

govultr.go, instance.go, instance_test.go, load_balancer.go, load_balancer_test.go, network.go, vpc.go, vpc_test.go
Add the new VPC data structures offered by the web API and put deprecation notices on the exported private network data types and functions.
=> Add Vultr VPC support

firewall_rule.go, firewall_rule_test.go
In firewall rules we are deprecating the `type` field in the get/list responses in favor of `ip_type`.
This will keep the field identical to what is used on the create call
=> Firewall Rules : adding `ip_type` 

bare_metal_server.go, instance.go, kubernetes.go
Change the update req structs so that `tag` can be deleted by sending an empty string.  Previously empty was ignored.
#221
=> Change tag to *string on update reqs

.github/workflows/coverage.yml, .github/workflows/gochecks.yml, .github/workflows/releaser.yml, govultr.go, govultr_test.go, instance.go, instance_test.go, kubernetes_test.go, load_balancer_test.go, network_test.go, reserved_ip_test.go, ssh_key_test.go, startup_script_test.go, user_test.go
Add golangci linting to github workflows and fix the go version in said workflows.
=> Add golangci and update go version in workflows

.github/workflows/coverage.yml, govultr_test.go
Linting changes prompted a test failure here.  Just remove the error handling like it was before updating to the new library.
Additionally, the codecov bot that was used before stopped working a while back so I think it's pertinent to remove the related actions for now.  The implementation uses deprecated github features and will need to be addressed when re-adding the codecov automation.
=> Fix context error in govultr test

database.go
Quick fix to allow empty DBaaS user password parameter to pass through to the Vultr API in order to automatically generate a secure new one. `omitempty` here was hitting a validation error since it removes the parameter from the request body altogether and it needs to at least be set as empty as a sort of user confirmation that they do indeed want to update the db user's password.
=> Allow empty password parameter on DBaaS user update

database.go
Database Engine and Database Engine Version are not usable in the update endpoint but were mistakenly included in the request object. This PR removes those.
=> Remove unused parameters from database update request

load_balancer.go, load_balancer_test.go
This PR will add the ability for govultr to set the amount of VLB nodes.
=> added vlb nodes

bare_metal_server.go, bare_metal_server_test.go, govultr.go, instance.go, instance_test.go, network.go, vpc.go, vpc2.go, vpc2_test.go
Add VPC 2.0.
VKE now automatically creates VPC 2.0. So VPC 2.0 is important to manage with Terraform.
I implemented it with reference to Vultr's API document and OpenAPI specification.
=> Add VPC 2.0

CHANGELOG.md, README.md, govultr.go
Remove all references and documentation relating to deprecated version of the Vultr API
=> Remove references to deprecated V1 API

database.go
Managed Database updates were failing to send an empty string to the Vultr API to detach VPCs, so this PR converts it into a pointer so it can safely be omitted, empty string, or VPCID string as the situation dictates.
=> Convert DatabaseUpdate VPCID to pointer for empty values

database.go
This PR updates Govultr to support the new API properties associated with the FerretDB offering for Vultr Managed Databases. The API docs already support "ferretpg" as a valid engine type upon launch, but the database results need to support to `ferretdb_credentials` object (and associated connection info) now returned from the API for those subscription types.
=> Add support for DBaaS FerretDB offering

kubernetes.go
Adds support for the `ha_controlplanes` field that was added to the API.  Setting this `true` will deploy the cluster with highly available control planes.
=> Add HA control planes support for VKE

database.go
This PR adds support for promoting Managed Database read-only replicas to their own standalone subscriptions to match the functionality in the customer portal and Vultr API.
=> Support read replica promotion for Managed Databases

kubernetes.go
Adds support for the `firewall_group_id` field that is now returned as part of VKE cluster responses.
Additionally adds support for `enable_firewall` which can be provided when creating a new VKE cluster. When enabled, a Firewall Group will be deployed and managed by the cluster, ensuring worker nodes are automatically linked to the firewall.
=> Add managed firewall support for VKE

.golangci.yaml, container_registry.go, container_registry_test.go, govultr.go, kubernetes.go, kubernetes_test.go, object_storage.go
* Add in support for all VCR operations except for the Kubernetes credentials (API changes required to make that operation work or #279 might suffice)
Check that the functions return data from the API:
```golang
func main() {
vultrClient, ctx := getClient()
// VCR -- comment/un-comment each to test
vcrGet(ctx, vultrClient)
vcrList(ctx, vultrClient)
vcrCreate(ctx, vultrClient)
vcrUpdate(ctx, vultrClient)
vcrDelete(ctx, vultrClient)
vcrListRepos(ctx, vultrClient)
vcrGetRepo(ctx, vultrClient)
vcrDeleteRepo(ctx, vultrClient)
vcrCreateDockerCredentials(ctx, vultrClient)
vcrListRegions(ctx, vultrClient)
vcrListPlans(ctx, vultrClient)
}
func getClient() (*govultr.Client, context.Context) {
apiKey := "YOUR API KEY"
config := &oauth2.Config{}
ctx := context.Background()
ts := …
```
=> Add support for container registry operations

container_registry.go, container_registry_test.go
Some minor fixes noticed while building out the CLI
=> Container registry data fixes

CHANGELOG.md, govultr.go
Release v3.4.1 #patch
#282 
#284
=> Release v3.4.1 #patch

bare_metal_server.go, govultr.go, instance.go, marketplace.go, marketplace_test.go
This PR introduces support for marketplace app variables over the Vultr API. Particularly, it includes an endpoint for listing user-supplied variables for a given marketplace app as well as a new `AppVariables` property that can be provided when creating VPS instances or BM servers. This should allow customers to finally use the Vultr API/open source libraries to deploy marketplace app instances when there are one or more required variable inputs, which was previously not possible.
=> Support Marketplace App Variables

kubernetes.go, kubernetes_test.go
Implements support for creating, updating and reading nodepool labels.
=> Add support for nodepool labels

startup_script.go
Adds the `omitempty` struct tag since it's the same struct used for update as is used for create.  As it is now, when updates are made, any empty values get sent to the API which will wipe the values.
#295
=> Allow empty values in startup script request struct

CHANGELOG.md, govultr.go
=> Release v3.6.4 #patch

bare_metal_server.go
The mdisk_mode param for baremetal create and update was recently added to the [vultr api](https://www.vultr.com/api/#tag/baremetal/operation/create-baremetal). 
This pull request will add the mdisk_mode param as a possible input for the BareMetalCreate and BareMetalUpdate structs.
=> [Feature] add MdiskMode to BareMetalCreate and BareMetalUpdate structs

cdn.go, govultr.go
Adds the service to support the CDN routes in the Vultr API
=> Add support for CDN

database.go
This PR adds support for Managed MySQL advanced configuration options using the existing endpoint that previously was exclusive to PostgreSQL. It functions exactly the same and the validation takes care of the distinction between the two database engine types.
=> Add support for Managed MySQL advanced config

bare_metal_server.go, firewall_rule.go, firewall_rule_test.go, instance.go
Bare Metal & Instance: remove deprecated `Tag` fields
Firewall: remove deprecated `Type` field
=> Remove deprecated Tag and Type fields

govultr.go, subaccount.go
Add support for the `/v2/subaccounts` API route
* `GET` : List
* `POST`: Create
=> Add support for sub-accounts

cdn.go
Removes some json marshalling tags and fixes an invalid path on the file endpoint route
=> Fix CDN structs and endpoint

database.go
This PR cleans up a few errant field names for the advanced configuration endpoint for the Managed Kafka product.
=> Fix Managed Kafka Advanced Config Field Naming

database.go
The Vultr API has been updated to support more generalized versions of certain fields such as `redis_eviction_policy` becoming just `eviction_policy` for Managed Databases and the various `DatabaseUserACL` fields. Old versions are still supported, but may not be in the future with different caching database engines.
=> Deprecate Redis-Named Fields

govultr.go, virtual_file_system_storage.go
This adds support for managing VFS storages.
You can emulate these test funcs to check each route available through the govultr library:
```go
func vfsList(ctx context.Context, client *govultr.Client) {
vfss, _, _, err := client.VirtualFileSystemStorage.List(ctx, nil)
if err != nil {
fmt.Println(err)
panic(err.Error())
}
fmt.Printf("%+v", vfss)
}
func vfsGet(ctx context.Context, client *govultr.Client) {
id := "0ae69c69-0c46-4ab3-8601-c86a39b1026e"
vfs, _, err := client.VirtualFileSystemStorage.Get(ctx, id)
if err != nil {
fmt.Println(err)
panic(err.Error())
}
fmt.Printf("%+v", vfs)
}
func vfsCreate(ctx context.Context, client *govultr.Client) {
vfs, _, err := client.VirtualFileSystemStorage.Create(ctx, &govultr.VirtualFileSystemStorageReq{
Region: "ewr",
Label:  "govultr-test", …
```
=> Add support for virtual file system storages

database.go
This PR removes previously-deprecated fields that were named specifically for Redis and cleans up a few other references (such as valid engine types for Managed Database plans). All services have been converted from Redis to Valkey, so the new, more generic-named fields should be used going forward.
=> Remove deprecated Redis references

load_balancer.go
=> Add AutoSSL and GlobalRegions to load balancers

load_balancer.go
=> Add missing load balancer SSL fields and AutoSSL struct

CHANGELOG.md, govultr.go
=> Release v3.14.1 #patch

account.go, account_test.go
Implements for [`/account/bandwidth`](https://www.vultr.com/api/#tag/account/operation/get-account-bandwidth) to `govultr`.
The implementation requires a type corresponding to JSON of e.g. this form:
```JSON
{
"bandwidth": {
"previous_month": {
"timestamp_start": "1735689600",
"timestamp_end": "1738367999",
"gb_in": 0,
"gb_out": 0,
"total_instance_hours": 1,
"total_instance_count": 1,
"instance_bandwidth_credits": 1,
"free_bandwidth_credits": 2048,
"purchased_bandwidth_credits": 0,
"overage": 0,
"overage_unit_cost": 0.01,
"overage_cost": 0
},
"current_month_to_date": {
"timestamp_start": "1738368000",
"timestamp_end": "1739577600",
"gb_in": 0,
"gb_out": 0,
"total_instance_hours": 0,
"total_instance_count": 0,
"instance_bandwidth_credits": 0,
"free_bandwidth_credits": 2048, …
```
=> Implements (and tests) `/account/bandwidth`

govultr.go, vpc2.go
VPC2 is being deprecated.  This annotates the services and structs with that notice.
=> Add go doc deprecation for VPC2 service and structs

object_storage.go, object_storage_test.go
Make object storage requests use value struct in order to conform with general API structure of the library now that more values are available for update in object storage.  This was left out in error from #365
=> Make object storage requests use value struct

database.go
This PR brings Govultr up to date on all the recent additions to the Vultr API for Managed Kafka subscriptions. It includes new API request fields for enabling Kafka REST, Schema Registry, and Kafka Connect, as well as response fields for the URIs to the REST and Schema Registry services. In addition, it includes the following new endpoints as a whole:
- `UpdateQuota`: New update endpoint for quotas (previous behavior required deleting and re-adding)
- `ListAvailableConnectors`: Shows all Kafka Connect connectors available for a subscription
- `GetConnectorConfigurationSchema`: Returns the configuration schema fields for a given connector
- `ListConnectors`: Lists all currently active connectors for a subscription
- `CreateConnector`, `GetConnector`, `UpdateConnector`, `DeleteConnector`: …
=> Managed Databases: Kafka Additional Feature Support

snapshot.go
NOTE: This field was historically a string which took `""`, `"no"`, or `"yes"`. The API has recently
been updated to take `true` and `false` booleans.
This adds the field as a `*bool` so that we can differentiate unset vs explicitly false.
Based on the current unit test setup, there isn't much point in adding coverage for this field.
Updated unit tests, and tested e2e manually with a corresponding update to the CLI: https://github.com/vultr/vultr-cli/pull/547
=> snapshots: Add support for CreateFromURL UEFI field
