vultr/govultr

.travis.yml
Use the latest Go releases (latest patch version). And also allow failures on `tip`, sometimes it can be broken.
none
=> Update to the latest Go releases

CHANGELOG.md, govultr.go
Release prep for v0.1.4
Primary code change:
#20
=> Release for v0.1.4

CHANGELOG.md, govultr.go
release for v0.1.5
releases #24
=> release for v0.1.5

CHANGELOG.md
Release for v0.1.6
Releases
#26
=> release for v0.1.6

CHANGELOG.md, govultr.go
Cutting a new release because my previous attempt at fixing a misaligned version failed.
none
=> release for v0.1.7

govultr.go, load_balancer.go, load_balancer_test.go
Going to create an lb-api feature branch and all new LB prs will go into that
Still need to write unit tests for these calls
#34
=> lb calls list,destroy,label,instance,healthcheck

load_balancer.go, load_balancer_test.go
Call to grab the generic info
#34
=> Lb genericinfo

load_balancer.go, load_balancer_test.go
=> LB forwarding rules

load_balancer.go, load_balancer_test.go
=> lb - get full conf

load_balancer.go, load_balancer_test.go
=> lb - ssl info

cmd/main.go, govultr.go, object_storage.go, object_storage_test.go
=> Object storage

CHANGELOG.md, govultr.go
release for GoVultr v0.2.0
#39
=> release for v0.2.0

object_storage.go, object_storage_test.go
The object storage get call will not return the data instead of an empty struct
Fixes  #45
=> Object Storage get call empty struct

CHANGELOG.md, govultr.go
Release for v0.3.0
Releases
#46 
#34 
Releases milestone v0.3.0
=> release for v0.3.0

load_balancer.go
Json response for this call has been changed. Updating the struct to reflect this
=> adjusting for API response change

load_balancer.go, load_balancer_test.go
Types were cleaned up on the API so adjusting the client to reflect that
Milestone 0.3.1
=> lb - type fix

CHANGELOG.md, govultr.go
Release for v0.3.1
#48
#50  
#51 
#53
=> release for v0.3.1

block_storage.go, block_storage_test.go
Adding ability to live attach/detach of blockstorage. 
Still need to write tests for this
=> live attach/detach of bs

CHANGELOG.md, govultr.go
=> release for v0.3.2

CHANGELOG.md, govultr.go
Release v0.3.3
Releases dep updates for go-retryablehttp
=> Release v0.3.3

load_balancer.go, object_storage.go
changed 'algorithm' to 'balancing_algorithm'
Fixes #60 
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ x] Have you linted your code locally prior to submission?
* [ x] Have you successfully ran tests with your changes locally?
=> Change 'algorithm' to 'balancing_algorithm' in LB create call

load_balancer.go, load_balancer_test.go
Adding the new functionality for the LB api to govultr
=> Lb updates

.travis.yml
=> Travis bump go versions

CHANGELOG.md, govultr.go
Release for v0.4.0 
Resolves #63, #62, #60
=> release for v0.4.0

load_balancer.go
This pointer should be checked if it is nil before using it
=> LB Create - handle pointer 

CHANGELOG.md, govultr.go
=> release for v0.4.1

CHANGELOG.md, govultr.go
=> release for v0.4.2

.travis.yml
Removing go 1.13
Adding go 1.15
=> removing go 1.13 and adding 1.15

server.go, server_test.go
API V1 introduced 
https://www.vultr.com/api/#server_ddos_protection_disable
https://www.vultr.com/api/#server_ddos_protection_enable
This PR adds support for these calls
closes #72
=> Add DDOS functionality

CHANGELOG.md, govultr.go
release for v0.5.0
https://github.com/vultr/govultr/milestone/3
=> Release v0.5.0

CHANGELOG.md, govultr.go
GoVultr is being promoted to v1. There aren't any code changes or breaking changes for this promotion. 
Moving forward all v1 code changes for govultr will be made against the v1 branch.
Relates to #80 
Closes #79
=> release for v1.0.0

firewall_rule.go, firewall_rule_test.go
=> add get call for firewall rule

instance.go
add enableprivatenetwork to instancereq struct
=> add enableprivatenetwork field to instances

README.md
=> v2 readme change

block_storage.go, block_storage_test.go, instance_test.go
Remove block resize function, it is handled in the update function
=> rm block resize

bare_metal_server.go, bare_metal_server_test.go, instance_test.go
Add getuserdata function, fix path names for several functions in file
=> V2 bm userdata

bare_metal_server.go, bare_metal_server_test.go, instance_test.go
Splits struct for update/create into two separate structs
=> separate bm struct into two for update and create

firewall_rule.go
fixes method for fw rule get()
=> V2 fw rule get

reserved_ip.go, reserved_ip_test.go
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x ] Have you linted your code locally prior to submission?
* [x ] Have you successfully ran tests with your changes locally?
=> V2 reservedip struct

regions.go, regions_test.go
makes planavailability exportable
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x ] Have you linted your code locally prior to submission?
* [x ] Have you successfully ran tests with your changes locally?
=> capitalize planavailability

instance.go, instance_test.go
fixes json field name in BackupSchedule struct
=> fix json field in backupschedule struct

bare_metal_server.go, bare_metal_server_test.go, instance.go, instance_test.go
Adding in the `/upgrades` call for Instances/Baremetals
=> v2 - instance/bm get upgrades

CHANGELOG.md, bare_metal_server.go, bare_metal_server_test.go, govultr.go, server.go, server_test.go
PR to release v1.1.0
I am merging this into the v1 branch and then will backfill into master.
Releases #100 Thanks @nsmith5
=> Release v1.1.0

CHANGELOG.md, go.mod, go.sum, govultr.go
I tagged the v1.1.0 release on the wrong branch 👎 . This patch release will fix be properly tagged and released .
=> release v1.1.1

bare_metal_server.go, bare_metal_server_test.go
adds response body for bare metal update and reinstall
=> add response body to bm update and reinstall

bare_metal_server.go, bare_metal_server_test.go
=> V2 updates into v2-api main branch

instance.go, instance_test.go
change type for backups and remove unneeded field
=> small struct changes

reserved_ip.go, user.go, user_test.go
Looks like there were a few issues that got past testing
n/a
=> patches for user + reserved ip

CHANGELOG.md, go.mod, govultr.go
Release for v2.1.0. Fixes 2 bugs found.
#112
=> releaes for v2.1.0

CHANGELOG.md, govultr.go
=> release for v2.2.0

CHANGELOG.md, govultr.go
=> Release v2.3.0

CHANGELOG.md, govultr.go
=> Release for v2.3.1

CHANGELOG.md, govultr.go
Release for v2.3.2
#122 : found a bug while cleaning up unit tests
=> release for v2.3.2

.github/workflows/notify-pr.yml
=> Notify PRs

.github/workflows/notify-release.yml
=> Notify release tags

README.md
Updated examples in the README.
#127
=> #127 update examples in README

README.md, account.go, application.go, backup.go, bare_metal_server.go, block_storage.go, domain_records.go, domains.go, firewall_group.go, firewall_rule.go, instance.go, iso.go, load_balancer.go, network.go, object_storage.go, os.go, plans.go, regions.go, reserved_ip.go, snapshot.go, ssh_key.go, startup_script.go, user.go
Added/updated the links to API v2
n/a
=> API v2 Links to godocs

CHANGELOG.md, README.md, govultr.go
=> v2.4.0 release

.travis.yml, CHANGELOG.md
Dep updates + travis bump to 1.15, 1.16, and tip for tests
#138  #137
=> release for v2.4.1

CHANGELOG.md, govultr.go
=> release for v2.4.2

CHANGELOG.md, govultr.go
=> release for v2.5.0

CHANGELOG.md, govultr.go
=> Release for v2.5.1

bare_metal_server.go, bare_metal_server_test.go
adding support for persistent_pxe 
n/a
=> BM : adding support for persistent_pxe

CHANGELOG.md, govultr.go
=> Release for v2.6.0

CHANGELOG.md, govultr.go
Release for v2.7.0
releases #150
=> Release for v2.7.0

bare_metal_server.go, instance.go
Adds ImageID to BM and Instance updates
=> add imageID for updates

CHANGELOG.md, govultr.go
Release for v2.7.1
releases #152
=> Release for v2.7.1

CHANGELOG.md, govultr.go
=> release for v2.8.0

.github/workflows/gochecks.yml, .travis.yml, go.mod, go.sum
Updating go version + builds to 1.16 from 1.14
=> bumping go versions to 1.16

CHANGELOG.md, govultr.go
=> release for v2.8.1

kubernetes.go, kubernetes_test.go
=> update k8 fields

CHANGELOG.md, govultr.go
=> Release v2.10.0

domains.go
Adding the field DNSSec for `dns_sec` which was added to the `get` call and will be added to other calls as well
Addresses #184
=> Domains : adding dns_sec to domains struct

instance.go
Any instance calls that return a full dataset of instances will also return the assigned hostname it has.
closes #186
=> instances will return the hostname that is assigned

load_balancer.go
Fix issue where SSL data wasn't being sent as proper json fields to the API
=> Bug : fix lb ssl issue to use proper json

CHANGELOG.md, govultr.go
=> release v2.11.1

plans.go
Fix the type for monthly pricing since certain regions can have surcharges which may have float pricing
#191
=> [Bug] : fix plan types to handle brazil

CHANGELOG.md, govultr.go
release for v2.12.0
fixes #191
=> release : v2.12.0

.github/workflows/releaser.yml
This PR fixes the regex for the auto releaser
=> Fixed regex for releaser

listOptions.go
Adding additional query params that can be used with ListOptions for Instance List call
#196
=> added list instance query params

CHANGELOG.md, govultr.go
Release for v2.13.0
Releases #196
=> Release v2.13.0 #minor

README.md
Replaces travis badge with gha
=> replace travis badge

listOptions.go
List instance calls now supports filtering for regions 
https://www.vultr.com/api/#operation/list-instances
=> Instances : add region as a supported list option

CHANGELOG.md, govultr.go
Release for v2.14.0
#200 
#202
=> Release v2.14.0 #minor

CHANGELOG.md, govultr.go
=> Release v2.14.1 #patch

CHANGELOG.md, govultr.go
=> Release 2.14.2 #patch

.github/workflows/gochecks.yml, .github/workflows/releaser.yml, go.mod
=> bumping go 1.16 to 1.17

CHANGELOG.md, govultr.go
Release for v2.15.0
#208 
#209 
#210
=> Release v2.15.0 #minor

block_storage.go
Allow omission of block_type on create
=> block type omit

kubernetes.go, kubernetes_test.go
This adds the two new endpoints relating to VKE upgrades
- get available upgrade versions
- starting an upgrade
=> Kubernetes: upgrade support

CHANGELOG.md, govultr.go
Release for v2.16.0
#214
#215 
#216 
#217 
#218
=> Release v2.16.0 #minor

plans.go
Add the GPU fields returned by the API for plans
=> Add GPU specific fields to plan struct

CHANGELOG.md, govultr.go
Release v2.17.1
[224](https://github.com/vultr/govultr/pull/224)
=> Release v2.17.1 #patch

reserved_ip.go, reserved_ip_test.go
Support the new PATCH API action for Reserved IP to update the label field.
=> Add support for updating reserved IP label

CHANGELOG.md
=> Release v2.17.2 #patch

.gitignore, go.mod
=> Update Go to v1.20

CHANGELOG.md, govultr.go
#235 
#239 
#240 
#238 
#236 
#241 
#234
=> Release v3.0.0 #major

CHANGELOG.md, README.md, go.mod
Updating module version and re-releasing
=> Release v3.0.1 #patch

CHANGELOG.md
=> Release v3.0.2 #patch

CHANGELOG.md, govultr.go
Release v3.2.0 #minor
#259 
#255
=> Release v3.2.0 #minor

CHANGELOG.md, govultr.go
=> Release v3.3.0 #minor

instance.go, network.go, vpc.go, vpc2.go, vpc2_test.go
This PR adds more of the API endpoints for VPC2, particularly listing attached nodes and mass attaching/detaching nodes for a given network.
=> Add VPC2 nodes endpoints

CHANGELOG.md, govultr.go
=> Release v3.3.1 #patch

CHANGELOG.md, govultr.go
Release v3.3.2 #patch
#266 
#268
=> Release v3.3.2 #patch

CHANGELOG.md, govultr.go
=> Release v3.3.3 #patch

CHANGELOG.md, govultr.go
Release v3.4.0 #minor
#276 
#277 
#278 
#280
=> Release v3.4.0 #minor

database.go
This PR implements support for the new Vultr API `/usage` endpoint for Managed Databases. It breaks up disk usage information (current/max/percentage) and memory/CPU usage details with the current values for the latter two reflecting an average over the last hour.
=> Add support for Managed Database usage endpoint

instance.go
Add disable IPv4 option to instance create request
=> Add disable IPv4 option to instance create request

database.go
This PR adds support for user access control for Redis Managed Database subscriptions. The updates include new list/get user response properties for Redis engine types as well as a new `/access-control` PUT request within the users to update the ACL configuration values.
=> Add support for Managed Database user access control for Redis

README.md
Update the README with non-authenticated client examples as well as some formatting and rewording
=> Update the README with non-auth client examples

CHANGELOG.md, govultr.go
Release v3.6.0 #minor
#291 
#290
=> Release v3.6.0 #minor

bare_metal_server.go
Add the functions to allow VPC on bare metal
=> Add the functions to allow VPC on bare metal

CHANGELOG.md, govultr.go
=> Release v3.6.1 #patch

CHANGELOG.md, govultr.go
=> Release v3.6.2 #patch

meta.go
Add the struct field tag for the links field in the meta struct
=> Add a json struct tag for the meta links field

.github/workflows/codeql-analysis.yml
The CodeQL runner v1 was deprecated and will not run.  This updates all codeql-actions to v2
=> Update codeql runner from v1 to v2

CHANGELOG.md, govultr.go
Release v3.6.3 #patch
#298 
#299 
#300
=> Release v3.6.3 #patch

kubernetes.go
Add labels to the update request struct.  This is necessary for node label updates.
=> Add labels to the node pool update request struct

.github/workflows/notify-issue.yml, .github/workflows/notify-pr.yml, .github/workflows/releaser.yml
Fix broken notifications from major version update
=> Update and fix mattermost notifications

.github/workflows/notify-issue.yml, .github/workflows/notify-pr.yml, .github/workflows/releaser.yml
Fix mattermost notifications
#305
=> Fix mattermost notifications

go.mod, go.sum
=> Update Go from v1.20 to v1.21

CHANGELOG.md, govultr.go
Release v3.7.0 #minor
#310 
#308 
#309 
#305 
#307
=> Release v3.7.0 #minor

.golangci.yaml, database.go, govultr.go, inference.go, inference_test.go
With the beta launch of Vultr Serverless Inference, this PR was put together to ensure this product is supported in our Go library.
=> Add Support for Vultr Serverless Inference

CHANGELOG.md, govultr.go
Release v2.8.0 #minor
#315 
#312 
#314
=> Release v2.8.0 #minor

CHANGELOG.md, govultr.go
=> Release v2.8.1 #patch

CHANGELOG.md, govultr.go
=> Release v3.9.0 #minor

cdn.go
* Fix the http method and variable name for the CDN push zone file deletion
=> Fix http method used on CDN push zone file delete

CHANGELOG.md, govultr.go
Release v3.9.1 #patch
#322 
#321
=> Release v3.9.1 #patch

load_balancer.go
Add request options to Load balancers:
* HTTP2
* HTTP3
* Timeout
Make firewall rules `omitempty` to only include in the request when defined.
=> Add http2/3 and timeout options to load balancers

cdn.go
* Add SSL options
* Add vanity domain option
=> Add vanity domain and SSL options to CDN

instance.go
* Add `UserScheme` field to the instance structs
=> Add instance user scheme field

subaccount.go
Uses a base struct to unmarshal the json from the create request.
=> Fix base struct for subaccount create

cdn_test.go, subaccount_test.go
Adds tests for the CDN and Sub-account functionality
=> Add CDN & Sub-account tests

go.mod, go.sum
Updates go version from v1.21 to v1.23
=> Update go from v1.21 to v1.23

.github/workflows/coverage.yml, .github/workflows/gochecks.yml, .github/workflows/releaser.yml
Bump the go versions on the github workflows
=> Update github workflows to go 1.23

bare_metal_server.go
Add the `user_scheme` options to bare metal update and create
Remove `omitempty` from required bare metal fields
#328
=> Add user scheme to bare metal

CHANGELOG.md, govultr.go
Release v3.10.0 #minor
#325 
#326 
#328 
#335 
#329 
#330 
#331 
#324 
#327 
#333 
#334 
#332
=> Release v3.10.0 #minor

.golangci.yaml
Remove deprecated exportloopref linter
=> Remove deprecated exportloopref linter

CHANGELOG.md, govultr.go
Release v3.11.0 #minor
#339 
#338 
#337
=> Release v3.11.0 #minor

database.go
This PR updates Govultr to make a bugfix on the Vultr API side and should be merged/released once that change hits the Vultr API.
=> Fix Quota Create endpoint param for Kafka

CHANGELOG.md, govultr.go
=> Release v3.11.1 #patch

CHANGELOG.md, govultr.go
=> Release v3.11.2 #patch

CHANGELOG.md, govultr.go
=> Release v3.12.0 #minor

CHANGELOG.md, govultr.go
=> Release v3.13.0 #minor

CHANGELOG.md, govultr.go
Release v3.14.0 #minor
#349 
#350
=> Release v3.14.0 #minor

billing.go, billing_test.go
Implements [`/billing/pending-charges`](https://www.vultr.com/api/#tag/billing/operation/pending-charges) to `govultr`
Fixes: #355
=> Implements (and tests) `/billing/pending-charges`

account.go
=> Fix whitespace

.github/workflows/coverage.yml, .github/workflows/gochecks.yml, .github/workflows/releaser.yml, go.mod
Update's the go version for go.mod and the github workflows.
=> Update Go from v1.23 to v1.24

CHANGELOG.md, govultr.go
Release v3.15.0 #minor
#356 
#357 
#359 
#360
=> Release v3.15.0 #minor

go.mod
Minimum go version does not need to be bumped as no lang features are being used which require it.
#362
=> Reset min go.mod go version to v1.23

CHANGELOG.md, govultr.go
Release v3.16.0 #minor
#365 
#364 
#367 
#366
=> Release v3.16.0 #minor

CHANGELOG.md, govultr.go
=> Release v3.16.1 #patch

bare_metal_server.go
Adds the iPXE URL create/update struct value
=> Add iPXE URL to bare metal

CHANGELOG.md, govultr.go
Release v3.18.0 #minor
#372 
#373
=> Release v3.18.0 #minor

bare_metal_server.go
Fix the URI used to detach VPCs from bare metal
=> Fix URI of bare metal VPC detach

kubernetes.go
Add VPC ID create parameter to kubernetes
=> Add VPC ID kubernetes create param

kubernetes.go
* Remove omitempty on node pool label update request otherwise you cannot delete the values in an update request
=> Remove omitempty on node pool label update request

CHANGELOG.md, govultr.go
=> Release v3.19.1 #patch

CHANGELOG.md, govultr.go
=> Release v3.20.0 #minor

CHANGELOG.md, govultr.go
=> Release v3.21.1 #patch

kubernetes.go
- Add node pool `user_data` to create/update structs
___
Enhancement
___
- Add `UserData` field to NodePool struct
- Add `UserData` to NodePoolReq create struct
- Add `UserData` pointer to NodePoolReqUpdate struct
- Enable user_data configuration for node pools
___
```mermaid
flowchart LR
NodePool["NodePool struct"] -->|"add"| UserData["UserData field"]
NodePoolReq["NodePoolReq struct"] -->|"add"| UserData
NodePoolReqUpdate["NodePoolReqUpdate struct"] -->|"add"| UserDataPtr["UserData pointer"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>kubernetes.go</strong><dd><code>Add user_data field to node pool …
=> Add node pool user_data to create/update structs

CHANGELOG.md, govultr.go
Release v3.22.0 #minor
#391
___
Enhancement
___
Bump library version to 3.22.0
Add Kubernetes node pool user_data support
Update CHANGELOG with release notes
___
```mermaid
flowchart LR
v3.21.1["v3.21.1"] -- "bump version" --> v3.22.0["v3.22.0"]
v3.22.0 -- "add user_data field" --> k8s["Kubernetes node pool structs"]
v3.22.0 -- "document changes" --> changelog["CHANGELOG.md"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>govultr.go</strong><dd><code>Update version constant to 3.22.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Release v3.22.0 #minor

.github/workflows/gochecks.yml, .golangci.yaml
Migrage golangci-lint config to v2
=> Migrate golangci-lint config to v2
